# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'  # Adjust the path to match the actual location of Dockerfile
        tags: |
          $(tag)

  - job: Push
    displayName: Push image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push image to container registry
      inputs:
        containerRegistry: 'excuseme-1493'  # Replace with your container registry name
        repository: 'excuseme'               # Replace with your repository name
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'          # Adjust the path to match the actual location of Dockerfile
        tags: |
          $(tag)
