apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-deployment
  labels:
    app: index
spec:
  replicas: 3
  selector:
    matchLabels:
      app: index
  template:
    metadata:
      labels:
        app: index
    spec:
      containers:
      - name: index-container
        image: excuseme:latest
        ports:
        - containerPort: 80
