apiVersion: v1
kind: Pod
metadata:
  name: excuseme-wa
  namespace: dev
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html-volume
    emptyDir: {}
  - name: config-volume
    configMap:
      name: excuseme-configmap
